# Generated by Django 3.1.3 on 2020-12-11 16:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_auto_20201211_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dhfao0jm7/image/upload/v1607673363/noImage_ipctvi.jpg', max_length=255, verbose_name='image'),
        ),
    ]
