# Generated by Django 3.1.3 on 2020-12-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0006_api_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_urls',
            name='url_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
