# Generated by Django 3.1.3 on 2020-12-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0007_api_urls_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_urls',
            name='url',
            field=models.URLField(max_length=50),
        ),
    ]
