# Generated by Django 3.1.3 on 2020-12-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0008_auto_20201213_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.CharField(choices=[('not selected', 'not selected'), ('EndSars', 'EndSars'), ('Covid-19', 'Covid-19')], default='not selected', max_length=30),
        ),
    ]
