# Generated by Django 3.1.3 on 2020-12-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0010_api_urls_how_to_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_urls',
            name='how_to_use',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
